In [ ]:
!pip install tld

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tld
  Downloading tld-0.12.6-py37-none-any.whl (412 kB)
     |████████████████████████████████| 412 kB 16.1 MB/s
Installing collected packages: tld
Successfully installed tld-0.12.6

In [ ]:
import pandas as pd
import numpy as np
import nltk
from nltk import wordpunct_tokenize
nltk.download('punkt')
import re
from collections import Counter
import csv
from tld import get_tld
from urllib.parse import urlparse

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving mendeley_test.csv to mendeley_test.csv

In [ ]:
data = pd.read_csv("mendeley_test.csv")

In [ ]:
data.head()

                                                urls  label
0               http://www.dutchthewiz.com/freeware/      0
1                   http://www.collectiblejewels.com      0
2                        http://www.deadlinedata.com      0
3  http://www.mil.fi/maavoimat/kalustoesittely/00...      0
4           http://www.avclub.com/content/node/24539      0

In [ ]:
print(data["label"].value_counts())

0    5000
1    5000
Name: label, dtype: int64

In [ ]:
urls = data["urls"]

In [ ]:
labels = data["label"]

In [ ]:
print(urls)
print(labels)

0                    http://www.dutchthewiz.com/freeware/
1                        http://www.collectiblejewels.com
2                             http://www.deadlinedata.com
3       http://www.mil.fi/maavoimat/kalustoesittely/00...
4                http://www.avclub.com/content/node/24539
                              ...
9995                http://www.freeadult2000.com/nonnude/
9996               http://www.malestrippersunlimited.com/
9997    http://www.troppobelle.net/disegni_a_matita/di...
9998    http://www.mature-nude-woman.com/older-women-p...
9999                http://www.anzwers.net/hot/maryblond/
Name: urls, Length: 10000, dtype: object
0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    1
9998    1
9999    1
Name: label, Length: 10000, dtype: int64

In [ ]:
def requrl(url):
  up = urlparse(url)
  nl = up.netloc
  query = up.query
  path = up.path
  params = up.params
  fragment = up.fragment


  try:
    res = get_tld(url, as_object=True)

    tld = res.tld
  except:
    print("No res")
    tld = " "

  # print(tld)
  urlparts = nl.rsplit(tld)
  urlpart = urlparts[0]

  required_url = urlpart+query+path+params+fragment

  # print("Final Url: ", required_url)
  return required_url

In [ ]:
def character_embedder(url):
    url = url.lower()
    char_arr = []
    char_arr.extend(url)
    tokens_count = Counter(url)
    url_vector = {}
    for i in char_arr:
      token_count = tokens_count[i]
      key = i
      value = token_count
      url_vector[key] = value
    return url_vector

In [ ]:

def character_count(url,label):
  url = url.lower()
  url = url.lower()
  char_arr = []
  char_arr.extend(url)
  tokens_count = Counter(url)
  for i in dictionary:
    token_count = tokens_count[i]
    key = i
    value = token_count
    if label == 0:
      genuine[key] += value
    if label == 1:
      malicious[key] += value

In [ ]:
def normalize(arr, t_min, t_max):
    norm_arr = []
    diff = t_max - t_min
    diff_arr = max(arr) - min(arr)
    if diff_arr == 0:
      for i in arr:
        temp = 1
        norm_arr.append(temp)
    else:
      for i in arr:
        temp = (((i - min(arr))*diff)/diff_arr) + t_min
        norm_arr.append(temp)

    return norm_arr

In [ ]:
def urlVector(url_vector):
  dictionary = "abcdefghijklmnopqrstuvwxyz0123456789!#$&|()*+,/:;=?@[]-_.~"
  url_vec = []
  for i in dictionary:
    if i in url_vector.keys():
      url_vec.append(url_vector.get(i))
    else:
      url_vec.append(0)
  return url_vec

In [ ]:
def vectocsv(url_vector, index):
  for j in dictionary:
      df[j][index] = url_vector[dictionary.index(j)]

In [ ]:
dictionary = "abcdefghijklmnopqrstuvwxyz0123456789!#$&|()*+,/:;=?@[]-_.~"
df = pd.DataFrame(np.nan, index = range(0, len(urls)), columns=[i for i in dictionary])

In [ ]:
df.head()

,a,b,c,d,e,f,g,h,i,j,...,;,=,?,@,[,],-,_,.,~
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df)

       a   b   c   d   e   f   g   h   i   j  ...   ;   =   ?   @   [   ]   -  \
0    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
1    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
2    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
3    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
4    NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..
9995 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
9996 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
9997 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
9998 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN
9999 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ... NaN NaN NaN NaN NaN NaN NaN

       _   .   ~
0    NaN NaN NaN
1    NaN NaN NaN
2    NaN NaN NaN
3    NaN NaN NaN
4    NaN NaN NaN
...   ..  ..  ..
9995 NaN NaN NaN
9996 NaN NaN NaN
9997 NaN NaN NaN
9998 NaN NaN NaN
9999 NaN NaN NaN

[10000 rows x 58 columns]

In [ ]:
index = 0
for url in urls:
  finalurl = requrl(url)
  url_vector = character_embedder(finalurl)
  vector = urlVector(url_vector)
  range_to_normalize = (0, 1)
  normalized_array_1d = normalize(vector, range_to_normalize[0], range_to_normalize[1])
  vectocsv(normalized_array_1d, index)
  index+=1

In [ ]:
label_index = 0
malicious = dict.fromkeys(dictionary, 0)
genuine = dict.fromkeys(dictionary, 0)
for url in urls:
  character_count(url, data["label"][label_index])
  label_index+=1

In [ ]:
print(malicious)

{'a': 159931, 'b': 65844, 'c': 129025, 'd': 94894, 'e': 176507, 'f': 60554, 'g': 52043, 'h': 94913, 'i': 130423, 'j': 13606, 'k': 21941, 'l': 82880, 'm': 107257, 'n': 106018, 'o': 141796, 'p': 132676, 'q': 7439, 'r': 87403, 's': 116253, 't': 185162, 'u': 54332, 'v': 22919, 'w': 52967, 'x': 22647, 'y': 25491, 'z': 12700, '0': 45022, '1': 49342, '2': 49191, '3': 37809, '4': 40438, '5': 38430, '6': 34974, '7': 34756, '8': 35664, '9': 34471, '!': 235, '#': 266, '$': 141, '&': 16216, '|': 93, '(': 268, ')': 165, '*': 334, '+': 164, ',': 335, '/': 207221, ':': 41650, ';': 13259, '=': 23327, '?': 10186, '@': 2375, '[': 32, ']': 37, '-': 26753, '_': 12495, '.': 101114, '~': 350}

In [ ]:
print(genuine)

{'a': 212342, 'b': 68839, 'c': 147843, 'd': 103404, 'e': 248305, 'f': 48339, 'g': 64949, 'h': 159233, 'i': 167025, 'j': 12423, 'k': 39393, 'l': 121588, 'm': 130167, 'n': 143549, 'o': 228273, 'p': 171872, 'q': 4737, 'r': 162435, 's': 188097, 't': 337507, 'u': 80127, 'v': 32305, 'w': 135496, 'x': 13518, 'y': 35674, 'z': 15237, '0': 54448, '1': 47138, '2': 43013, '3': 28089, '4': 23075, '5': 24427, '6': 20749, '7': 21425, '8': 32707, '9': 23994, '!': 77, '#': 213, '$': 17, '&': 10401, '|': 0, '(': 130, ')': 142, '*': 26, '+': 1753, ',': 0, '/': 312265, ':': 86095, ';': 248, '=': 19581, '?': 9092, '@': 35, '[': 0, ']': 0, '-': 123741, '_': 15370, '.': 165247, '~': 132}

In [ ]:
with open('D3_count_gen.csv', 'w') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames = genuine.keys())
    writer.writeheader()
    writer.writerow(genuine)

In [ ]:
with open('D3_count_mal.csv', 'w') as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames = malicious.keys())
    writer.writeheader()
    writer.writerow(malicious)

In [ ]:
df.head()

,a,b,c,d,e,f,g,h,i,j,...,;,=,?,@,[,],-,_,.,~
0,0.200000,0.000000,0.200000,0.200000,0.800000,0.2,0.0,0.4,0.200000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.400000,0.0
1,0.000000,0.250000,0.500000,0.000000,1.000000,0.0,0.0,0.0,0.250000,0.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.500000,0.0
2,1.000000,0.000000,0.000000,1.000000,0.666667,0.0,0.0,0.0,0.333333,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.666667,0.0
3,1.000000,0.000000,0.000000,0.250000,0.750000,0.0,0.0,0.0,0.750000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.25,0.750000,0.0
4,0.333333,0.333333,0.666667,0.333333,0.666667,0.0,0.0,0.0,0.000000,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.666667,0.0

In [ ]:
print(df)

             a         b         c         d         e         f         g  \
0     0.200000  0.000000  0.200000  0.200000  0.800000  0.200000  0.000000
1     0.000000  0.250000  0.500000  0.000000  1.000000  0.000000  0.000000
2     1.000000  0.000000  0.000000  1.000000  0.666667  0.000000  0.000000
3     1.000000  0.000000  0.000000  0.250000  0.750000  0.000000  0.000000
4     0.333333  0.333333  0.666667  0.333333  0.666667  0.000000  0.000000
...        ...       ...       ...       ...       ...       ...       ...
9995  0.333333  0.000000  0.000000  0.666667  1.000000  0.333333  0.000000
9996  0.333333  0.000000  0.000000  0.333333  1.000000  0.000000  0.000000
9997  1.000000  0.166667  0.000000  0.333333  0.833333  0.000000  0.333333
9998  0.400000  0.000000  0.200000  0.600000  1.000000  0.000000  0.000000
9999  0.500000  0.250000  0.000000  0.250000  0.250000  0.000000  0.000000

             h         i     j  ...    ;    =    ?    @    [    ]    -  \
0     0.400000  0.200000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     0.000000  0.250000  0.25  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     0.000000  0.333333  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     0.000000  0.750000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     0.000000  0.000000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...        ...       ...   ...  ...  ...  ...  ...  ...  ...  ...  ...
9995  0.000000  0.000000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9996  0.000000  1.000000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9997  0.333333  1.000000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
9998  0.200000  0.400000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.8
9999  0.250000  0.000000  0.00  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

             _         .    ~
0     0.000000  0.400000  0.0
1     0.000000  0.500000  0.0
2     0.000000  0.666667  0.0
3     0.250000  0.750000  0.0
4     0.000000  0.666667  0.0
...        ...       ...  ...
9995  0.000000  0.666667  0.0
9996  0.000000  0.666667  0.0
9997  0.833333  0.500000  0.0
9998  0.000000  0.600000  0.0
9999  0.000000  0.500000  0.0

[10000 rows x 58 columns]

In [ ]:
df.to_csv("mendeley_test_featues.csv")